import type { Lang } from "../../i18n";
import type { AgiAgentId } from "./types";

const en = {
  agi: "AGI Mode",
  agiLayer: "AGI Mode · agentic AI team",
  agiOn: "AGI Mode on",
  agiOff: "AGI Mode off",
  normalAi: "Normal AI",
  toggleOn: "Turn AGI Mode on",
  toggleOff: "Turn AGI Mode off",
  promise: "Give TOUR24 a business objective. Your AI team coordinates the work and brings you the decisions that need your attention.",
  askAgi: "What do you want your AI team to achieve?",
  askAgiHint: "Give an objective. The team plans and stops at approvals.",
  askAgiPh: "Prepare a six-day Golden Triangle inbound tour for 40 Chinese travelers…",
  attach: "Attach",
  askAgiIngestHint: "Attach a brief. The team extracts facts; nothing is held.",
  assign: "Assign objective",
  flagship: "Use the Golden Triangle inbound brief",
  pause: "Pause mission",
  resume: "Resume mission",
  takeover: "Take over",
  normalHelp: "Normal AI helps with one task: draft a message, check a margin, suggest a day.",
  agiHelp: "AGI Mode takes an objective and authority. The team plans, coordinates modules, executes permitted actions, and stops at approvals.",
  confirmed: "Confirmed",
  estimate: "Estimate",
  missing: "Missing",
  watchQuote: "A polished itinerary is not a booking. Rooms and seats stay requested until a human confirms.",
  options: "Package options",
  jobs: "Specialist jobs",
  blockers: "Blockers",
  approvals: "Approvals needed",
  deadlines: "Deadlines",
  impact: "Financial impact",
  authority: "Authority",
  spend: "Spend without approval",
  floor: "Discount floor / margin",
  cannotConfirm: "Cannot confirm inventory",
  canQuote: "May request supplier quotes",
  changeOnce: "Change Once → Coordinate Everything",
  changeRun: "Customer now 32 travelers",
  changeApply: "Authorize change plan",
  rescue: "AI Trip Rescue",
  rescueRun: "Arrival delayed 3h",
  rescuePick: "Authorize this recovery",
  oneCommand: "One Command → Complete Tour Project",
  agentDirect: "Agent Direct — sell to the customer’s AI",
  later: "Local engine is live. Remote models stay unplugged until you add an API key.",
  agentsTitle: "Operations team",
  ingest: "Brief ingest",
  ingestHint: "Paste or upload. .txt / .csv / .json are read as text. PDF and voice are recorded uploads — fields come from the filename or demo, not live speech-to-text.",
  ingestPaste: "Paste brief",
  ingestFile: "Upload file",
  ingestGo: "Extract fields",
  jobsWait: "Jobs waiting",
  supplierReplied: "Supplier replied / resume",
  memory: "Company memory",
  memoryValid: "Valid",
  scorecards: "Agent scorecards",
  adapter: "Provider adapter: local engine",
  adapterHint: "Grok, Claude and ChatGPT are not wired. Prices and margins stay on this engine.",
  negotiation: "Supplier Negotiation Room",
  normalize: "Normalized inclusions",
  roundAuth: "Authorize next round",
  roundReply: "Mark supplier replied",
  viaPortal: "No API — reply via /portal/supplier",
  notCommitment: "Extract / quote ≠ commitment. Nothing is held.",
  autopilot: "Departure Profit Autopilot",
  committed: "Committed cost",
  estimatedCost: "Estimated cost",
  recPrice: "Recommend price",
  recRelease: "Release rooms",
  recPromote: "Promote seats",
  recVehicle: "Change vehicle",
  rehearsal: "AI Trip Rehearsal",
  rehearsalRun: "Run this case",
  fragile: "Fragile connection",
  assumption: "Visible assumption",
  tapAccept: "Accept TAP brief",
  tapJson: "Structured TAP JSON",
  tapExternal: "External agents see sell price only",
  tapInternal: "Internal keep cost and margin",
  pastePh: "Paste an email, CSV, JSON or TAP brief…",
  offTitle: "AGI Mode is off",
  offBody: "You are in Normal AI. Ask for one task, or turn AGI Mode on to assign an objective to the team.",
  written: "Written to Operator OS records",
  notSecured: "Not secured",
  waitingSupplier: "Waiting on supplier",
  active: "Active missions",
  completed: "Completed actions",
  supplierIn: "Supplier responses",
};

const th: typeof en = {
  ...en,
  agi: "โหมด AGI",
  agiLayer: "โหมด AGI · ทีมเอเจนต์",
  agiOn: "เปิดโหมด AGI",
  agiOff: "ปิดโหมด AGI",
  normalAi: "AI ปกติ",
  toggleOn: "เปิดโหมด AGI",
  toggleOff: "ปิดโหมด AGI",
  promise: "ให้ TOUR24 รับวัตถุประสงค์ทางธุรกิจ ทีม AI ประสานงานแล้วส่งเฉพาะตัดสินใจที่คุณต้องแตะ",
  askAgi: "อยากให้ทีม AI ทำให้ถึงไหน?",
  askAgiHint: "มอบวัตถุประสงค์ ทีมวางแผนแล้วหยุดที่จุดอนุมัติ",
  askAgiPh: "จัดอินบาวด์สามเหลี่ยมทองคำ 6 วัน สำหรับกรุ๊ปจีน 40 คน…",
  attach: "แนบไฟล์",
  askAgiIngestHint: "แนบบรีฟ ทีมดึงข้อเท็จจริง ไม่ถือของ",
  assign: "มอบวัตถุประสงค์",
  flagship: "ใช้บรีฟอินบาวด์สามเหลี่ยมทองคำ",
  pause: "พักภารกิจ",
  resume: "ทำต่อ",
  takeover: "รับงานเอง",
  normalHelp: "AI ปกติช่วยทีละงาน: ร่างข้อความ ดูมาร์จิ้น เสนอวัน",
  agiHelp: "โหมด AGI รับวัตถุประสงค์และอำนาจ ทีมวางแผน ประสานโมดูล ทำในกรอบที่อนุญาต แล้วหยุดที่จุดอนุมัติ",
  confirmed: "ยืนยันแล้ว",
  estimate: "ประมาณการ",
  missing: "ยังขาด",
  watchQuote: "โปรแกรมที่สวยยังไม่ใช่การจอง ห้องและที่นั่งเป็น requested จนกว่าคนจะคอนเฟิร์ม",
  options: "ตัวเลือกแพ็กเกจ",
  jobs: "งานผู้เชี่ยวชาญ",
  blockers: "สิ่งที่บล็อก",
  approvals: "รออนุมัติ",
  deadlines: "เดดไลน์",
  impact: "ผลทางการเงิน",
  authority: "อำนาจที่ให้ทีม",
  spend: "ใช้จ่ายได้โดยไม่อนุมัติ",
  floor: "พื้นส่วนลด / มาร์จิ้น",
  cannotConfirm: "ห้ามยืนยันคลังสินค้า",
  canQuote: "ขอใบเสนอซัพพลายเออร์ได้",
  changeOnce: "เปลี่ยนครั้งเดียว → ประสานทั้งหมด",
  changeRun: "ลูกค้าเหลือ 32 คน",
  changeApply: "อนุมัติแผนเปลี่ยนแปลง",
  rescue: "กู้ทริปด้วย AI",
  rescueRun: "ไฟลต์ขาเข้าดีเลย์ 3 ชม.",
  rescuePick: "อนุมัติแผนกู้",
  oneCommand: "คำสั่งเดียว → โปรเจกต์ทัวร์ครบ",
  agentDirect: "Agent Direct — ขายให้ AI ของลูกค้า",
  later: "เอนจินท้องถิ่นทำงานแล้ว โมเดลระยะไกลยังไม่ต่อ จนกว่าคุณจะใส่ API key",
  agentsTitle: "ทีมปฏิบัติการ",
  ingest: "รับบรีฟจากไฟล์",
  ingestHint: "วางหรืออัปโหลด .txt / .csv / .json อ่านเป็นข้อความ PDF และเสียงบันทึกการอัปโหลด — ฟิลด์มาจากชื่อไฟล์หรือเดโม ไม่ถอดเสียงจริง",
  ingestPaste: "วางบรีฟ",
  ingestFile: "อัปโหลดไฟล์",
  ingestGo: "ดึงฟิลด์",
  jobsWait: "งานที่รอ",
  supplierReplied: "ซัพพลายเออร์ตอบ / ทำต่อ",
  memory: "ความจำบริษัท",
  memoryValid: "ใช้ได้",
  scorecards: "สกอร์การ์ดเอเจนต์",
  adapter: "อะแดปเตอร์: เอนจินท้องถิ่น",
  adapterHint: "ยังไม่ต่อ Grok / Claude / ChatGPT ราคาและมาร์จิ้นอยู่ที่เอนจินนี้",
  negotiation: "ห้องเจรจาซัพพลายเออร์",
  normalize: "อินคลูชันที่จัดแล้ว",
  roundAuth: "อนุมัติรอบถัดไป",
  roundReply: "บันทึกว่าซัพพลายเออร์ตอบ",
  viaPortal: "ไม่มี API — ตอบที่ /portal/supplier",
  notCommitment: "ข้อความที่ดึง ≠ ข้อผูกพัน ยังไม่ถือของ",
  autopilot: "ออโตไพลอตกำไรรอบเดินทาง",
  committed: "ต้นทุนที่ผูกแล้ว",
  estimatedCost: "ต้นทุนประมาณ",
  recPrice: "แนะนำราคา",
  recRelease: "ปล่อยห้อง",
  recPromote: "โปรโมทที่นั่ง",
  recVehicle: "เปลี่ยนรถ",
  rehearsal: "ซ้อมทริปด้วย AI",
  rehearsalRun: "รันเคสนี้",
  fragile: "จุดเปราะ",
  assumption: "สมมติฐานที่เห็น",
  tapAccept: "รับบรีฟ TAP",
  tapJson: "JSON โครงสร้าง TAP",
  tapExternal: "เอเจนต์ภายนอกเห็นราคาขายเท่านั้น",
  tapInternal: "ภายในเก็บต้นทุนและมาร์จิ้น",
  pastePh: "วางอีเมล CSV JSON หรือบรีฟ TAP…",
  offTitle: "โหมด AGI ปิดอยู่",
  offBody: "ตอนนี้เป็น AI ปกติ ถามทีละงาน หรือเปิดโหมด AGI เพื่อมอบวัตถุประสงค์ให้ทีม",
  written: "เขียนลงเรคคอร์ด Operator OS แล้ว",
  notSecured: "ยังไม่ล็อกของ",
  waitingSupplier: "รอซัพพลายเออร์",
  active: "ภารกิจที่กำลังทำ",
  completed: "งานที่ทำแล้ว",
  supplierIn: "คำตอบซัพพลายเออร์",
};

const zh: typeof en = {
  ...en,
  agi: "AGI 模式",
  agiLayer: "AGI 模式 · 智能体团队",
  agiOn: "AGI 已开",
  agiOff: "AGI 已关",
  normalAi: "普通 AI",
  toggleOn: "打开 AGI 模式",
  toggleOff: "关闭 AGI 模式",
  promise: "给 TOUR24 一个业务目标。AI 团队协调工作，只把需要你拍板的决定送来。",
  askAgi: "你希望 AI 团队达成什么？",
  askAgiHint: "下达目标。团队规划，在批准处停下。",
  attach: "附加",
  askAgiIngestHint: "附上简报。团队抽取事实，不锁库存。",
  assign: "下达目标",
  flagship: "使用金三角入境团简报",
  pause: "暂停任务",
  resume: "继续",
  takeover: "人工接管",
  confirmed: "已确认",
  estimate: "估算",
  missing: "缺失",
  changeOnce: "改一次 → 全线协调",
  rescue: "AI 行程救援",
  oneCommand: "一条指令 → 完整团项目",
  offTitle: "AGI 模式已关闭",
};

const ru: typeof en = {
  ...en,
  agi: "Режим AGI",
  agiLayer: "Режим AGI · агентная команда",
  agiOn: "AGI включён",
  agiOff: "AGI выключен",
  normalAi: "Обычный ИИ",
  toggleOn: "Включить AGI",
  toggleOff: "Выключить AGI",
  promise: "Дайте TOUR24 бизнес-цель. Команда ИИ координирует работу и приносит решения, которые требуют вас.",
  askAgi: "Чего должна добиться команда ИИ?",
  askAgiHint: "Поставьте цель. Команда планирует и останавливается на согласованиях.",
  attach: "Вложить",
  askAgiIngestHint: "Прикрепите бриф. Команда извлечёт факты, ничего не бронируется.",
  assign: "Поставить цель",
  flagship: "Бриф: inbound Золотой треугольник",
  pause: "Пауза",
  resume: "Продолжить",
  takeover: "Перехватить",
  confirmed: "Подтверждено",
  estimate: "Оценка",
  missing: "Не хватает",
  changeOnce: "Одно изменение → вся координация",
  rescue: "AI-спасение тура",
  oneCommand: "Одна команда → полный проект",
  offTitle: "Режим AGI выключен",
};

export const AGI_COPY = { en, th, zh, ru };

export function agiCopy(lang: Lang) {
  return { ...en, ...AGI_COPY[lang] };
}

const AGENT_EN: Record<AgiAgentId, { name: string; role: string }> = {
  director: { name: "AI Tour Director", role: "Turns the objective into jobs, dependencies and a close." },
  sales: { name: "AI Sales & Quotation", role: "Fills the brief, versions quotes, follows the comms policy." },
  itinerary: { name: "AI Itinerary Designer", role: "Builds a workable day plan around time, meals and access." },
  flight: { name: "AI Group Flight", role: "Requests group fares and tracks blocks, names and tickets." },
  hotel: { name: "AI Hotel", role: "Compares rates, rooming lists, release dates and alternatives." },
  bus: { name: "AI Bus & Transport", role: "Matches vehicles, drivers and transfer buffers." },
  venue: { name: "AI Restaurant & Attraction", role: "Capacity, diet, tickets and reservation state." },
  guide: { name: "AI Guide & Trip Ops", role: "Assigns guides, briefings, manifests and daily ops." },
  service: { name: "AI Traveler Service", role: "Answers from the confirmed plan; escalates the rest." },
  finance: { name: "AI Profit & Finance", role: "Margin, deposits, payables and actual trip profit." },
  quality: { name: "AI Quality & Supplier Intel", role: "Late acks, failures, invoice gaps, operator memory." },
};

const AGENT_TH: Record<AgiAgentId, { name: string; role: string }> = {
  director: { name: "ผู้อำนวยการทัวร์ AI", role: "แปลงวัตถุประสงค์เป็นงาน ลำดับ และปิดทริป" },
  sales: { name: "ขายและใบเสนอ AI", role: "เติมบรีฟ ออกใบเสนอหลายฉบับ ตามนโยบายสื่อสาร" },
  itinerary: { name: "ออกแบบโปรแกรม AI", role: "จัดวันที่ใช้ได้จริง ตามเวลา อาหาร และการเข้าถึง" },
  flight: { name: "ไฟลต์กลุ่ม AI", role: "ขอเรทกลุ่ม ติดตามบล็อก รายชื่อ และตั๋ว" },
  hotel: { name: "โรงแรม AI", role: "เทียบเรท รูมมิ่ง วันปล่อย และทางเลือก" },
  bus: { name: "รถและขนส่ง AI", role: "จับรถ คนขับ และบัฟเฟอร์รับส่ง" },
  venue: { name: "ร้านอาหารและสถานที่ AI", role: "ความจุ อาหารพิเศษ ตั๋ว สถานะจอง" },
  guide: { name: "ไกด์และปฏิบัติการ AI", role: "จัดไกด์ บรีฟ แมนิเฟสต์ งานรายวัน" },
  service: { name: "บริการผู้เดินทาง AI", role: "ตอบจากแผนที่ยืนยัน เรื่องด่วนส่งคน" },
  finance: { name: "กำไรและการเงิน AI", role: "มาร์จิ้น มัดจำ เจ้าหนี้ กำไรจริง" },
  quality: { name: "คุณภาพและซัพพลายเออร์ AI", role: "ตอบช้า บริการพัง ใบแจ้งหนี้ไม่ตรง ความจำบริษัท" },
};

export function agentMeta(lang: Lang, id: AgiAgentId) {
  return lang === "th" ? AGENT_TH[id] : AGENT_EN[id];
}

export const AGENT_ORDER: AgiAgentId[] = [
  "director",
  "sales",
  "itinerary",
  "flight",
  "hotel",
  "bus",
  "venue",
  "guide",
  "service",
  "finance",
  "quality",
];
