import type { Lang } from "../i18n";

const en = {
  os: "Operator OS",
  osSystem: "AI tour operating system",
  product: "TOUR24 OS",
  home: "Operations",
  sales: "Sales",
  builder: "Tour builder",
  departure: "Departure",
  flights: "Group flights",
  suppliers: "Suppliers",
  live: "Live trip",
  finance: "Finance",
  analytics: "Analytics",
  portals: "Portals",
  scope: "Scope map",
  ask: "Ask AI",
  askAi: "Ask AI",
  askHint: "Type a task. AI drafts; you apply it to records.",
  askPh: "Add 5 passengers, delay CZ3051, check passports, show margin…",
  attach: "Attach",
  askIngestHint: "Drop a quote, email, or sheet. You apply the draft.",
  attached: "Attached",
  voice: "Voice",
  listening: "Listening…",
  voiceStop: "Stop",
  voiceUnsupported: "This browser cannot listen. Type or attach a file.",
  askVoiceHint: "Speak a brief, quote, or change (e.g. 32 pax).",
  run: "Run acceptance demo",
  reset: "Reset demo",
  today: "Today’s departures",
  urgent: "Urgent deadlines",
  unconf: "Unresolved confirmations",
  margin: "Margin alerts",
  await: "Awaiting approval",
  happened: "What happened",
  why: "Why it matters",
  money: "Financial effect",
  next: "Proposed next action",
  indicative: "Indicative",
  quoted: "Quoted",
  held: "Held",
  confirmed: "Confirmed",
  source: "Source",
  updated: "Updated",
  apply: "Apply to records",
  edit: "Edit",
  approve: "Approve",
  add5: "Add 5 passengers",
  delay: "Delay arrival flight",
  close: "Close departure",
  pax: "Passengers",
  rooms: "Rooms",
  meals: "Meals",
  acts: "Activities",
  buses: "Transport",
  guides: "Guides",
  docs: "Documents",
  overview: "Overview",
  sold: "Sold",
  unsold: "Unsold",
  exposure: "Exposure",
  names: "Name list",
  ticket: "Ticketing",
  compare: "Compare offers",
  ack: "Acknowledge",
  traveler: "Traveller",
  organiser: "Organiser",
  supplier: "Supplier",
  guide: "Guide",
  demo: "Acceptance demo",
  demoLine: "40-person inbound Golden Triangle from a Chinese group enquiry. Allocate services, add five passengers, delay the Chiang Mai arrival, approve, confirm, close on actual profit.",
  channels: "Sales channels",
  marketplace: "Marketplace",
  website: "Booking website",
  agents: "Agent Direct",
  b2b: "B2B portal",
  playbook: "Playbook",
  hidePlaybook: "Hide playbook",
  showPlaybook: "Open playbook",
  playbookGoal: "What this menu is for",
  playbookWatch: "Watch",
  playbookAi: "Ask the OS",
  playbookSteps: "How to work this screen",
  playbookThis: "This menu",
  agi: "AGI Mode",
};

const th: typeof en = {
  ...en,
  os: "ระบบปฏิบัติการทัวร์",
  osSystem: "ระบบปฏิบัติการทัวร์ด้วย AI",
  product: "TOUR24 OS",
  home: "ปฏิบัติการ",
  sales: "ขาย",
  builder: "สร้างทัวร์",
  departure: "รอบเดินทาง",
  flights: "ไฟลต์กลุ่ม",
  suppliers: "ซัพพลายเออร์",
  live: "ทริปสด",
  finance: "การเงิน",
  analytics: "วิเคราะห์",
  portals: "พอร์ทัล",
  scope: "แผนขอบเขต",
  ask: "ถาม AI",
  askAi: "ถาม AI",
  askHint: "พิมพ์งานทีละอย่าง AI ร่างให้ คุณใส่ลงเรคคอร์ดเอง",
  askPh: "เพิ่ม 5 คน, ดีเลย์ CZ3051, เช็กพาสปอร์ต, ดูมาร์จิ้น…",
  attach: "แนบไฟล์",
  askIngestHint: "วางใบเสนอ อีเมล หรือชีต คุณเป็นคนใส่ร่างลงเรคคอร์ด",
  attached: "แนบแล้ว",
  voice: "เสียง",
  listening: "กำลังฟัง…",
  voiceStop: "หยุด",
  voiceUnsupported: "เบราว์เซอร์นี้ฟังไม่ได้ พิมพ์หรือแนบไฟล์แทน",
  askVoiceHint: "พูดบรีฟ ใบเสนอ หรือการเปลี่ยน (เช่น 32 คน)",
  run: "รันเดโมรับงาน",
  reset: "รีเซ็ตเดโม",
  today: "รอบเดินทางวันนี้",
  urgent: "เดดไลน์ด่วน",
  unconf: "คอยืนยัน",
  margin: "เตือนมาร์จิ้น",
  await: "รออนุมัติ",
  happened: "เกิดอะไร",
  why: "ทำไมสำคัญ",
  money: "ผลทางการเงิน",
  next: "ขั้นถัดไปที่เสนอ",
  indicative: "ราคาประมาณ",
  quoted: "ใบเสนอ",
  held: "ถือของ",
  confirmed: "ยืนยันแล้ว",
  source: "แหล่งข้อมูล",
  updated: "อัปเดต",
  apply: "ใส่ลงเรคคอร์ด",
  edit: "แก้ไข",
  approve: "อนุมัติ",
  add5: "เพิ่มผู้โดยสาร 5 คน",
  delay: "ดีเลย์ไฟลต์ขาเข้า",
  close: "ปิดรอบเดินทาง",
  pax: "ผู้โดยสาร",
  rooms: "ห้องพัก",
  meals: "อาหาร",
  acts: "กิจกรรม",
  buses: "รถ",
  guides: "ไกด์",
  docs: "เอกสาร",
  overview: "ภาพรวม",
  sold: "ขายแล้ว",
  unsold: "เหลือ",
  exposure: "ความเสี่ยง",
  names: "รายชื่อ",
  ticket: "ออกตั๋ว",
  compare: "เทียบข้อเสนอ",
  ack: "ตอบรับ",
  traveler: "ผู้เดินทาง",
  organiser: "ผู้จัดกรุ๊ป",
  supplier: "ซัพพลายเออร์",
  guide: "ไกด์",
  demo: "เดโมรับงาน",
  demoLine: "อินบาวด์สามเหลี่ยมทองคำ 40 คนจากกรุ๊ปจีน จัดไฟลต์เข้าเชียงใหม่ โรงแรม รถ อาหาร กิจกรรม เพิ่ม 5 คน ดีเลย์ไฟลต์ขาเข้า อนุมัติ ติดตามยืนยัน ปิดด้วยกำไรจริง",
  channels: "ช่องทางขาย",
  marketplace: "มาร์เก็ตเพลส",
  website: "เว็บจอง",
  agents: "Agent Direct",
  b2b: "พอร์ทัลเอเย่นต์",
  playbook: "เพลย์บุ๊ก",
  hidePlaybook: "ซ่อนเพลย์บุ๊ก",
  showPlaybook: "เปิดเพลย์บุ๊ก",
  playbookGoal: "เมนูนี้ทำอะไร",
  playbookWatch: "ระวัง",
  playbookAi: "ถามระบบ",
  playbookSteps: "วิธีทำงานในหน้านี้",
  playbookThis: "เมนูนี้",
  agi: "โหมด AGI",
};

const zh: typeof en = {
  ...en,
  os: "运营商系统",
  osSystem: "AI 旅游操作系统",
  home: "运营",
  sales: "销售",
  builder: "线路搭建",
  departure: "发团",
  flights: "团队机票",
  suppliers: "供应商",
  live: "出团现场",
  finance: "财务",
  analytics: "分析",
  portals: "门户",
  scope: "范围对照",
  ask: "问 AI",
  askAi: "问 AI",
  askHint: "输入一项任务。AI 起草，由你写入记录。",
  attach: "附加",
  askIngestHint: "放下报价、邮件或表格。由你把草稿写入记录。",
  attached: "已附加",
  voice: "语音",
  listening: "正在听…",
  voiceStop: "停止",
  voiceUnsupported: "此浏览器无法听写。请输入或附加文件。",
  askVoiceHint: "口述简报、报价或变更（例如 32 人）。",
  run: "运行验收演示",
  reset: "重置演示",
  approve: "批准",
  add5: "增加 5 位客人",
  delay: "延误抵达航班",
  close: "关闭发团",
  playbook: "作业手册",
  hidePlaybook: "收起手册",
  showPlaybook: "打开手册",
  playbookGoal: "这个菜单做什么",
  playbookWatch: "注意",
  playbookAi: "问系统",
  playbookSteps: "本屏作业步骤",
  playbookThis: "本菜单",
  agi: "AGI 模式",
};

const ru: typeof en = {
  ...en,
  os: "ОС туроператора",
  osSystem: "ИИ-система туроператора",
  home: "Операции",
  sales: "Продажи",
  builder: "Конструктор",
  departure: "Заезд",
  flights: "Групповые рейсы",
  suppliers: "Поставщики",
  live: "Живой тур",
  finance: "Финансы",
  analytics: "Аналитика",
  portals: "Порталы",
  scope: "Карта объёма",
  ask: "Спросить ИИ",
  askAi: "Спросить ИИ",
  askHint: "Одна задача. ИИ готовит черновик, вы пишете в записи.",
  attach: "Вложить",
  askIngestHint: "Перетащите КП, письмо или таблицу. Черновик применяете вы.",
  attached: "Вложено",
  voice: "Голос",
  listening: "Слушаю…",
  voiceStop: "Стоп",
  voiceUnsupported: "Браузер не умеет слушать. Введите текст или вложите файл.",
  askVoiceHint: "Надиктуйте бриф, КП или изменение (напр. 32 чел.).",
  run: "Приёмочное демо",
  reset: "Сброс демо",
  approve: "Утвердить",
  add5: "Добавить 5 пассажиров",
  delay: "Задержать прилёт",
  close: "Закрыть заезд",
  playbook: "Плейбук",
  hidePlaybook: "Скрыть плейбук",
  showPlaybook: "Открыть плейбук",
  playbookGoal: "Зачем это меню",
  playbookWatch: "Осторожно",
  playbookAi: "Спросить ОС",
  playbookSteps: "Как работать на этом экране",
  playbookThis: "Это меню",
  agi: "Режим AGI",
};

export const OS = { en, th, zh, ru };

export function osCopy(lang: Lang) {
  return { ...en, ...OS[lang] };
}
