import type { Lang } from "../i18n";

const en = {
  os: "Operator OS",
  product: "TOUR24 OS",
  home: "Operations",
  sales: "Sales",
  builder: "Tour builder",
  departure: "Departure",
  flights: "Group flights",
  suppliers: "Suppliers",
  live: "Live trip",
  finance: "Finance",
  analytics: "Analytics",
  portals: "Portals",
  scope: "Scope map",
  ask: "Ask the OS",
  askPh: "Add 5 passengers, delay TG660, check passports, show margin…",
  run: "Run acceptance demo",
  reset: "Reset demo",
  today: "Today’s departures",
  urgent: "Urgent deadlines",
  unconf: "Unresolved confirmations",
  margin: "Margin alerts",
  await: "Awaiting approval",
  happened: "What happened",
  why: "Why it matters",
  money: "Financial effect",
  next: "Proposed next action",
  indicative: "Indicative",
  quoted: "Quoted",
  held: "Held",
  confirmed: "Confirmed",
  source: "Source",
  updated: "Updated",
  apply: "Apply to records",
  edit: "Edit",
  approve: "Approve",
  add5: "Add 5 passengers",
  delay: "Delay arrival flight",
  close: "Close departure",
  pax: "Passengers",
  rooms: "Rooms",
  meals: "Meals",
  acts: "Activities",
  buses: "Transport",
  guides: "Guides",
  docs: "Documents",
  overview: "Overview",
  sold: "Sold",
  unsold: "Unsold",
  exposure: "Exposure",
  names: "Name list",
  ticket: "Ticketing",
  compare: "Compare offers",
  ack: "Acknowledge",
  traveler: "Traveller",
  organiser: "Organiser",
  supplier: "Supplier",
  guide: "Guide",
  demo: "Acceptance demo",
  demoLine: "40-person outbound Tokyo from a corporate enquiry. Allocate services, add five passengers, delay the arrival, approve, confirm, close on actual profit.",
  channels: "Sales channels",
  marketplace: "Marketplace",
  website: "Booking website",
  agents: "Agent Direct",
  b2b: "B2B portal",
  playbook: "Playbook",
  hidePlaybook: "Hide playbook",
  showPlaybook: "Open playbook",
  playbookGoal: "What this menu is for",
  playbookWatch: "Watch",
  playbookAi: "Ask the OS",
  playbookSteps: "How to work this screen",
  playbookThis: "This menu",
};

const th: typeof en = {
  ...en,
  os: "ระบบปฏิบัติการทัวร์",
  product: "TOUR24 OS",
  home: "ปฏิบัติการ",
  sales: "ขาย",
  builder: "สร้างทัวร์",
  departure: "รอบเดินทาง",
  flights: "ไฟลต์กลุ่ม",
  suppliers: "ซัพพลายเออร์",
  live: "ทริปสด",
  finance: "การเงิน",
  analytics: "วิเคราะห์",
  portals: "พอร์ทัล",
  scope: "แผนขอบเขต",
  ask: "ถามระบบ",
  askPh: "เพิ่ม 5 คน, ดีเลย์ TG660, เช็กพาสปอร์ต, ดูมาร์จิ้น…",
  run: "รันเดโมรับงาน",
  reset: "รีเซ็ตเดโม",
  today: "รอบเดินทางวันนี้",
  urgent: "เดดไลน์ด่วน",
  unconf: "คอยืนยัน",
  margin: "เตือนมาร์จิ้น",
  await: "รออนุมัติ",
  happened: "เกิดอะไร",
  why: "ทำไมสำคัญ",
  money: "ผลทางการเงิน",
  next: "ขั้นถัดไปที่เสนอ",
  indicative: "ราคาประมาณ",
  quoted: "ใบเสนอ",
  held: "ถือของ",
  confirmed: "ยืนยันแล้ว",
  source: "แหล่งข้อมูล",
  updated: "อัปเดต",
  apply: "ใส่ลงเรคคอร์ด",
  edit: "แก้ไข",
  approve: "อนุมัติ",
  add5: "เพิ่มผู้โดยสาร 5 คน",
  delay: "ดีเลย์ไฟลต์ขาเข้า",
  close: "ปิดรอบเดินทาง",
  pax: "ผู้โดยสาร",
  rooms: "ห้องพัก",
  meals: "อาหาร",
  acts: "กิจกรรม",
  buses: "รถ",
  guides: "ไกด์",
  docs: "เอกสาร",
  overview: "ภาพรวม",
  sold: "ขายแล้ว",
  unsold: "เหลือ",
  exposure: "ความเสี่ยง",
  names: "รายชื่อ",
  ticket: "ออกตั๋ว",
  compare: "เทียบข้อเสนอ",
  ack: "ตอบรับ",
  traveler: "ผู้เดินทาง",
  organiser: "ผู้จัดกรุ๊ป",
  supplier: "ซัพพลายเออร์",
  guide: "ไกด์",
  demo: "เดโมรับงาน",
  demoLine: "ทัวร์ขาออกโตเกียว 40 คนจากงานลูกค้า จัดไฟลต์ โรงแรม รถ อาหาร กิจกรรม เพิ่ม 5 คน ดีเลย์ไฟลต์ อนุมัติ ติดตามยืนยัน ปิดด้วยกำไรจริง",
  channels: "ช่องทางขาย",
  marketplace: "มาร์เก็ตเพลส",
  website: "เว็บจอง",
  agents: "Agent Direct",
  b2b: "พอร์ทัลเอเย่นต์",
  playbook: "เพลย์บุ๊ก",
  hidePlaybook: "ซ่อนเพลย์บุ๊ก",
  showPlaybook: "เปิดเพลย์บุ๊ก",
  playbookGoal: "เมนูนี้ทำอะไร",
  playbookWatch: "ระวัง",
  playbookAi: "ถามระบบ",
  playbookSteps: "วิธีทำงานในหน้านี้",
  playbookThis: "เมนูนี้",
};

const zh: typeof en = {
  ...en,
  os: "运营商系统",
  home: "运营",
  sales: "销售",
  builder: "线路搭建",
  departure: "发团",
  flights: "团队机票",
  suppliers: "供应商",
  live: "出团现场",
  finance: "财务",
  analytics: "分析",
  portals: "门户",
  scope: "范围对照",
  ask: "问系统",
  run: "运行验收演示",
  reset: "重置演示",
  approve: "批准",
  add5: "增加 5 位客人",
  delay: "延误抵达航班",
  close: "关闭发团",
  playbook: "作业手册",
  hidePlaybook: "收起手册",
  showPlaybook: "打开手册",
  playbookGoal: "这个菜单做什么",
  playbookWatch: "注意",
  playbookAi: "问系统",
  playbookSteps: "本屏作业步骤",
  playbookThis: "本菜单",
};

const ru: typeof en = {
  ...en,
  os: "ОС туроператора",
  home: "Операции",
  sales: "Продажи",
  builder: "Конструктор",
  departure: "Заезд",
  flights: "Групповые рейсы",
  suppliers: "Поставщики",
  live: "Живой тур",
  finance: "Финансы",
  analytics: "Аналитика",
  portals: "Порталы",
  scope: "Карта объёма",
  ask: "Спросить ОС",
  run: "Приёмочное демо",
  reset: "Сброс демо",
  approve: "Утвердить",
  add5: "Добавить 5 пассажиров",
  delay: "Задержать прилёт",
  close: "Закрыть заезд",
  playbook: "Плейбук",
  hidePlaybook: "Скрыть плейбук",
  showPlaybook: "Открыть плейбук",
  playbookGoal: "Зачем это меню",
  playbookWatch: "Осторожно",
  playbookAi: "Спросить ОС",
  playbookSteps: "Как работать на этом экране",
  playbookThis: "Это меню",
};

export const OS = { en, th, zh, ru };

export function osCopy(lang: Lang) {
  return { ...en, ...OS[lang] };
}
